apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-worker
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: transform-exporter
  template:
    metadata:
      labels:
        k8s-app: transform-exporter
    spec:
      containers:
        - name: task-worker
          image: nginx
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: task-worker
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-worker
  minReplicas: 1
  maxReplicas: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 10
          periodSeconds: 10
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 10
          periodSeconds: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: transform_task_queue_size
      target:
        averageValue: 10
        type: AverageValue
