apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: inst
  namespace: monitoring
spec:
  serviceMonitorSelector:
    matchLabels:
      k8s-app: transform-exporter
  resources:
    requests:
      memory: 400Mi